name: Python flake8 lint check

# This workflow is triggered on pushes to any branch in the repository.
on: push

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the latest version of Python 3.

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run flake8
      run: flake8 .
      # You can also modify the line above to pass additional arguments to flake8. For example:
      # run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      # This command checks the code for most errors (E9), most other issues (F63, F7, F82), shows the source of each issue, and provides a count at the end.

